#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://123.59.62.104:3306/wxapp_timeticket?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: user_timeticket
#    password: timeticket20190323qaz#

spring:
  datasource:
    url: jdbc:h2:mem:RealH2InUserd;DB_CLOSE_DELAY=-1;MODE=MYSQL
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

swagger:
  enable: true