#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://123.59.62.104:3306/wxapp_timeticket?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: user_timeticket
#    password: timeticket20190323qaz#

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.29.229.56:8081/health_diet?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: health
    password: ENC(rGNiKeTCh+6ytetsg/jE3VDACK7LpM5koTX8Xd7NPYI=)

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

swagger:
  enable: true